#!/usr/bin/env node
/**
 * Creates the event a load test runs against, and prints its ids.
 *
 * The k6 scenarios need an event that already has a ticket type assigned to every seat;
 * doing that inside the test would measure the organizer flow instead of the booking flow.
 *
 *   node loadtest/seed.mjs --seats 5000
 *   node loadtest/seed.mjs --json > /tmp/event.json
 */

const BASE = process.env.BASE_URL || 'http://localhost:8080';
const args = process.argv.slice(2);
const asJson = args.includes('--json');
const seatArg = args.indexOf('--seats');
const wantedSeats = seatArg >= 0 ? Number(args[seatArg + 1]) : null;
const userArg = args.indexOf('--users');
const userCount = userArg >= 0 ? Number(args[userArg + 1]) : 0;
const outArg = args.indexOf('--out');
const outFile = outArg >= 0 ? args[outArg + 1] : 'loadtest/results/users.json';

const log = (...m) => { if (!asJson) console.error(...m); };

async function call(path, { method = 'GET', body, token } = {}) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;

  const response = await fetch(`${BASE}${path}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body),
  });

  const text = await response.text();
  if (!response.ok) {
    throw new Error(`${method} ${path} -> ${response.status} ${text}`);
  }
  return text ? JSON.parse(text) : undefined;
}

const stamp = Date.now();
const email = `loadtest-organizer-${stamp}@tickify.test`;
const password = 'Passw0rd!';

log('Registering organizer', email);
await call('/api/v1/auth/register', {
  method: 'POST',
  body: { email, password, requestedRoles: ['ORGANIZER', 'USER'] },
});

const { accessToken } = await call('/api/v1/auth/login', {
  method: 'POST',
  body: { email, password },
});

const venues = await call('/api/v1/venue/', { token: accessToken });
if (!venues.length) throw new Error('No venues seeded — start the app with SEED_ENABLED=true');

// The seat map's size is the main lever on contention, so pick deliberately: the venue
// closest to --seats when asked, otherwise simply the largest available.
const sorted = [...venues].sort((a, b) => b.seatCount - a.seatCount);
const venue = wantedSeats
  ? [...venues].sort(
      (a, b) => Math.abs(a.seatCount - wantedSeats) - Math.abs(b.seatCount - wantedSeats),
    )[0]
  : sorted[0];

log(`Using venue "${venue.name}" (${venue.seatCount} seats) of ${venues.length} available`);

const start = new Date(Date.now() + 30 * 24 * 3600 * 1000);
const event = await call('/api/v1/events/', {
  method: 'POST',
  token: accessToken,
  body: {
    title: `Load Test Drop ${stamp}`,
    description: 'Generated by loadtest/seed.mjs',
    venue_id: venue.id,
    startDate: start.toISOString(),
    endDate: new Date(start.getTime() + 3 * 3600 * 1000).toISOString(),
    ticketSaleStartDate: new Date().toISOString(),
    ticketSaleEndDate: new Date(start.getTime() - 3600 * 1000).toISOString(),
  },
});
log('Created event', event.id);

const ticketType = await call('/api/v1/ticket-types/', {
  method: 'POST',
  token: accessToken,
  body: {
    title: 'General Admission',
    description: 'Load test tier',
    event_id: event.id,
    price: 49.99,
    totalQuantity: 100000,
  },
});
log('Created ticket type', ticketType.id);

// Every seat has to carry a ticket type before it can be sold.
await call('/api/v1/event-seats/assign-ticket-type', {
  method: 'POST',
  token: accessToken,
  body: { eventId: event.id, ticketTypeId: ticketType.id },
});

const seats = await call(`/api/v1/events/${event.id}/seats/available`, { token: accessToken });
log(`Event is on sale with ${seats.length} available seats`);

// Pre-provision shopper accounts.
//
// Registering inside the test looked reasonable until the first run: password hashing is
// bcrypt, which is expensive on purpose, and at a few hundred sign-ups a second it consumed
// most of the CPU on the box. The measurement was of bcrypt, not of booking. Accounts are
// therefore created up front, outside the measured window, and the test reuses their tokens.
if (userCount > 0) {
  log(`Provisioning ${userCount} shopper accounts (bcrypt is slow by design; this takes a while)`);
  const tokens = [];
  const CONCURRENCY = 8;

  for (let start = 0; start < userCount; start += CONCURRENCY) {
    const batch = [];
    for (let i = start; i < Math.min(start + CONCURRENCY, userCount); i++) {
      const shopperEmail = `loadtest-shopper-${stamp}-${i}@tickify.test`;
      batch.push(
        call('/api/v1/auth/register', {
          method: 'POST',
          body: { email: shopperEmail, password, requestedRoles: ['USER'] },
        })
          .then(() => call('/api/v1/auth/login', { method: 'POST', body: { email: shopperEmail, password } }))
          .then((auth) => auth.accessToken),
      );
    }
    tokens.push(...(await Promise.all(batch)));
    if ((start + CONCURRENCY) % 100 < CONCURRENCY) log(`  ${tokens.length}/${userCount}`);
  }

  const { writeFileSync, mkdirSync } = await import('node:fs');
  const { dirname } = await import('node:path');
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, JSON.stringify(tokens));
  log(`Wrote ${tokens.length} access tokens to ${outFile}`);
}

const result = {
  eventId: event.id,
  ticketTypeId: ticketType.id,
  availableSeats: seats.length,
  firstSeatId: seats[0]?.id,
  venue: venue.name,
};

if (asJson) {
  console.log(JSON.stringify(result, null, 2));
} else {
  console.error('');
  console.error('Run a scenario with:');
  console.error(`  k6 run -e EVENT_ID=${result.eventId} -e TICKET_TYPE_ID=${result.ticketTypeId} \\`);
  console.error('    loadtest/scenarios/ticket-drop.js');
  console.log(`EVENT_ID=${result.eventId}`);
  console.log(`TICKET_TYPE_ID=${result.ticketTypeId}`);
  console.log(`SEAT_ID=${result.firstSeatId}`);
  console.log(`AVAILABLE_SEATS=${result.availableSeats}`);
}
